apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis
  name: redis-service
  annotations:
    configsync.gke.io/cluster-name-selector: anthos-gke
spec:
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: redis
  type: LoadBalancer
